### ISSUE TITLE
New feature importances aren't written when replacing an existing model

### ISSUE THREAD

**Issue by shaycrk** [dssg/catwalk#32]
`ModelTrainer._write_model_to_db()` returns before processing feature importances if it finds existing metadata for the model in the database (for instance, when trying to re-run a model with `replace=True`) -- see [line 140](https://github.com/dssg/catwalk/blob/master/catwalk/model_trainers.py#L140) of model_trainers.py. As a result, replaced models will be associated with the old, incorrect, feature importances from a previous run.

Relatedly, another side-effect of this behavior is that models that get re-run don't receive an updated run time or batch run time in the database, with the models table reflecting when the model was initially run, not most recently.

**Comment by thcrock** [comment]
if i'm reading this right, you're referring to an existing bug, i think. there is an open PR! https://github.com/dssg/catwalk/pull/25

**Comment by shaycrk** [comment]
Ah, I missed that PR, but looks like that should address this! Are you just waiting on testing/approval to merge it in?

**Comment by shaycrk** [comment]
Closing this since we addressed by merging #25
